### ISSUE TITLE
OTP Showing Incorrect Program Name

### ISSUE THREAD

**Issue by ChakshuGautam** [AmakrushAI/user-service#1]
@aashutosh-samagra connect with @choxx

**Comment by choxx** [comment]
Change the template variable in the respective environment file & re-deploy the service.
https://github.com/AmakrushAI/user-service/blob/master/.env.sample#L8

**Comment by aashutosh-samagra** [comment]
@ChakshuGautam , can u assign someone to take this up?

**Comment by ChakshuGautam** [comment]
@singhalkarun can you take this up?

**Comment by ChakshuGautam** [comment]
@aashutosh-samagra do we have an approved template now? 

https://enterprise.smsgupshup.com/login
vikas.kumar@gupshup.io should be able to help.

**Comment by aashutosh-samagra** [comment]
We can use the below template @singhalkarun  - 
"Dear User!,  the One Time Password (OTP) to log in to AmaKrushAI is xxxx. This OTP will be valid for the next 5 mins."

@choxx can you update this for AKAI OTPs.

**Comment by aashutosh-samagra** [comment]
Template has been approved by Gupshup. @singhalkarun can u check this

**Comment by ChakshuGautam** [comment]
@singhalkarun to share an update.

**Comment by singhalkarun** [comment]
> Dear User!, the One Time Password (OTP) to log in to AmaKrushAI is xxxx. This OTP will be valid for the next 5 mins.

Updated the .env with new gupshup template as shared in https://github.com/AmakrushAI/user-service/issues/1#issuecomment-1516056668

**Comment by ChakshuGautam** [comment]
- [x] Get user service APIs up and running
- [x] Link Admin to user service - login
- [ ] Link the frontend to this user service @geeky-abhishek () - updated OTP template
- [ ] jwt => `sub` == `UserId`; Need to send this to user feedback API; Transport socket will use the same; @ChakshuGautam to make changes on the transport socket.
- [ ] @Amruth-Vamshi to update user service to add users to Flagsmith (A/B Testing)
- [ ] @prtkjakhar to update firebase to send this userId as one of the parameters
- [ ] @prtkjakhar to integrate console errors with firebase crashlytics

**Comment by aashutosh-samagra** [comment]
Revised template - 

Dear User!, the One Time Password (OTP) to log in to AmaKrushAI is @__123__@. This OTP will be valid for the next @__123__@ minutes. - Samagra

Template name - AmakrushAI_Login_OTP

**Comment by ChakshuGautam** [comment]
@singhalkarun to update the env variable the API for user-service.

**Comment by singhalkarun** [comment]
@aashutosh-samagra @ChakshuGautam the current template is 
`Hi User! The OTP to reset password for Samagra Shiksha App is %code%.` 

What variable should be used for expiry time in new template?

`Dear User!, the One Time Password (OTP) to log in to AmaKrushAI is %code%. This OTP will be valid for the next %{variable_name}% minutes. - Samagra`

**Comment by aashutosh-samagra** [comment]
Do we have any OTP expiration timeline ?
If not, then we can stick to the standard '5 minutes' timeline

**Comment by singhalkarun** [comment]
Cool, for now updated it to this. @ChakshuGautam @aashutosh-samagra 

`Dear User!, the One Time Password (OTP) to log in to AmaKrushAI is %code%. This OTP will be valid for the next 5 minutes. - Samagra`
